exclude:
  - .arcconfig
  - .gitignore
  - .npmignore
  - CHANGELOG.md
  - bower.json
  - coffeelint.json
  - gul[pfile.coffee
  - package-lock.json
  - package.json

include:
  - dist/
  - dist/html-docx.js
  - src/
  - test/
  - LICENSE
  - README.md

timezone: America/Phoenix
